### ISSUE TITLE
Brno: Todo-list for import

### ISSUE THREAD

**Issue by HirschSt** [rism-international/import#6]
- [ ] clearify RISM-id MAIL
- [x] correct leader
- [x] add 852 datafield with siglum, probably from 910, siglum: 
- [x] add url for the original entry; url see eg https://vufind.mzk.cz/Record/MZK01-001258266
- [ ] how about linkage between collection and entry; sf $3 for linkage?
- [x] correct Names with taling comma
- [x] add 240 if not existent
- [x] move 856$y 856$z
- [x] correct inipit number
- [x] set provider in 040$a (and "DE-633" in $c)
- [x] clear material block (probably add $8 01) in 260, 300...
- [x] add some translations MAIL
- [x] remove "cmp" from 100
